#!/usr/bin/env python3
# coding=utf-8
# Created by sharp.gan at 2017-09-01
# Above automatically generated by github.com/supersu097/EZcode4CLI

import json
import requests
import os
from core import helper

hot_url='https://www.v2ex.com/api/topics/hot.json'

def data_paser():
    data = requests.get(hot_url).text
    return json.loads(data)

def id_persistence():
    if not os.path.isfile('id_data.txt'):
        with open('id_data.txt', 'a+') as f:
            for i in data_paser():
                f.write(str(i['id']) + '\n')

def check_new():
    if os.path.isfile('id_data.txt'):
        with open('id_data.txt') as f:
            old_id_list = [_.rstrip() for _ in f.readlines()]
            new_id_list = [str(_['id']) for _ in data_paser() if str(_['id']) not in old_id_list]
            
            """

                    for data_collection in data_paser():
                        for new_id in new_id_list:
                            if new_id == str(data_collection['id']):
                                helper.mail_send('V2ex: ' + data_collection['title'],
                                        data_collection['url'])
               """
            print(data_paser())

if __name__ == '__main__':
    id_persistence()
    check_new()
