#!/usr/bin/env python3
# coding=utf-8
# Created by sharp.gan at 2017-09-04
# Above automatically generated by github.com/supersu097/EZcode4CLI

import json

import requests
from bs4 import BeautifulSoup
from selenium import webdriver

from core import helper


def page_source_get(url):
    try:
        rep_data = requests.get(url).text
        if url.split('.')[-1] == 'json':
            return json.loads(rep_data)
        else:
            return rep_data

    except requests.exceptions.RequestException:
        helper.logger_getter().error('Network connection error')
        exit(1)


def first_aTag_extract(url, rule):
    soup = BeautifulSoup(page_source_get(url), 'html5lib')
    firstURL = soup.select(rule)[0]
    return firstURL


def make_screenshot(url, filename):
    driver = webdriver.PhantomJS(executable_path=helper.CURR_PATH + '/core/phantomjs-2.1.1')
    driver.get(url)
    driver.execute_script('document.body.style.background = "white"')
    driver.implicitly_wait(20)
    driver.save_screenshot(filename)
    driver.quit()
